version: '3.1'

services:
   db_mysql:
      container_name: db_mysql
      image: mysql
      ports:
         - "3311:3306"
      restart: always
      environment:
         MYSQL_USER: user_spring
         MYSQL_PASSWORD: spring123
         MYSQL_ROOT_PASSWORD: root1q2w3e4r
      volumes:
         - /home/user/mysql/db:/var/lib/mysql
   phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin
      restart: always
      ports:
         - "80:80"
      environment:
         PMA_HOST: db_mysql
      depends_on:
         - db_mysql