server:
  port: 8083
spring:
  application:
    name: apigateway
routes:
  - id: Product
    uri: http://localhost:8085/
    predicates:
      - Path=/products/**
  - id: Store
    uri: http://localhost:8086/
    predicates:
      - Path=/storage/**